### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ainame** [ainame/frameit-swift#2]

**Comment by Amzd** [comment]
Hi, I'd love to continue this even though there has not been much development on this for a while.

Missing a readme and examples it's a bit hard to figure out how even use it. Would love to chat.

**Comment by ainame** [comment]
I've been using this at work but have not had a chance to write README or a blog post. Right now I've been focusing on contributing to other project but will dedicate some time to improve this. Stay tuned. In the meantime, I will leave a simple note to start using this tonight hopefully...

**Comment by Amzd** [comment]
Ok good to hear, looking forward to it.

**Comment by Amzd** [comment]
Hey, just checking up on this. I'd love to start using this.

**Comment by ainame** [comment]
I'd leave a simple note here. 

1. `gem install fastlane` & `fastlane frameit download_frames` (FrameKit uses device frame images generated by frameit)
2. `git clone https://github.com/ainame/FrameKit.git`
3. `swift run framekit-gen` you'll see help text 
4. Prepare a screenshot taken with iPhone 11 Pro Max simulator

This has a sample layout by default. You can give it try first.
For example, you can run this command to generate a screenshot having framed screenshot with text just like what fastlane frameit generates.

```
$ swift run framekit-gen --layout iphone_65 \
                         --locale en_US \
                         --keyword "Hello World" \
                         --title "Make a beautiful screenshot!" \
                         --device-frame "~/.fastlane/frameit/latest/Apple\ iPhone\ 11\ Pro\ Max\ Silver.png"
                         --screenshots "a screenshot's path taken with iPhone 11 Pro Max simulator"
                         --output sample.jpg
```

If you want to change layout, you can modify view file `Sources/DefaultFrameKitLayout/AppScreenshotView+DefaultLayout.swift` with SwiftUI or adjust font size in `DefaultLayout.swift`.

I don't use the `framekit-gen` cli directly but instead, I integrate this with a custom runner script which is private at this moment. As you can see here, CLI is just a wrapper of this.  

https://github.com/ainame/FrameKit/blob/7aee676c44a18c8b8a0ba3b1aac1e9a63691cc99/Sources/FrameKitGenCLI/Command.swift#L58-L74

**Comment by ainame** [comment]
@Amzd Hope this makes sense 🤞

**Comment by ainame** [comment]
I reckon there's a lot of rooms to improve before officially publishing this so those steps may not work in future.

**Comment by ainame** [comment]
FrameKit got many updates, and I finally finished the basic README update. I still have to update inline class documents but hope README initially helps people who are interested.

**Comment by aehlke** [comment]
This helped understand what you use the CLI for. I was a bit confused about that. It'd help if you'd suggest in the readme what to use to trigger the CLI - I see you may have it integrated with a test runner invoking it according to the PDF of the talk you gave on this library. thanks

**Comment by ainame** [comment]
@aehlke What do you refer to by "the CLI"? This project doesn't contain CLI support but is just a chunk of components as a library. You can use it in your SPM-based executable app. Since the layout code is supposed to be written in Swift, you have to compile your layout code within your app right now, which is why this project doesn't provide the CLI frontend part.
